[package]
name = "smc"
version = "0.1.0"
authors = ["lrusso96 <russo.1699981@studenti.uniroma1.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
